# Generated by Django 4.2 on 2023-04-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
